[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = " newbie-oogway"
authors = [{name = "Steve", email = "1301637976@qq.com"}]
dynamic = ["version", "description"]
